# Generated by Django 6.0.3 on 2026-03-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hospital",
            name="distance",
            field=models.FloatField(default=0),
        ),
    ]
