# Generated by Django 6.0.3 on 2026-03-26 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_hospital_distance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sosrequest",
            name="emergency_type",
            field=models.CharField(max_length=200),
        ),
    ]
