# Generated by Django 6.0.3 on 2026-03-28 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_user_preferences"),
    ]

    operations = [
        migrations.AddField(
            model_name="sosrequest",
            name="is_for_self",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="sosrequest",
            name="third_party_condition",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sosrequest",
            name="third_party_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="sosrequest",
            name="third_party_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
