# Generated by Django 6.0.3 on 2026-03-28 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_sosrequest_is_for_self_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sosrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("SEARCHING", "Searching"),
                    ("ASSIGNED", "Assigned"),
                    ("RESOLVED", "Resolved"),
                ],
                default="SEARCHING",
                max_length=20,
            ),
        ),
    ]
